name: 构建 Tauri 桌面版本
on:
  - push
  - workflow_dispatch
jobs:
  clean-pre-release:
    name: 删除预发布版本的构建产物
    runs-on: ubuntu-22.04
    steps:
      - name: 删除预发布版本的构建产物
        uses: mknejp/delete-release-assets@v1
        with:
          token: ${{ github.token }}
          assets: >
            *.*
          tag: ${{ github.ref_name }}-dev
          fail-if-no-assets: false
          fail-if-no-release: false
  build-tauri-desktop:
    name: 构建 Tauri 桌面版本
    needs: clean-pre-release
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: windows-latest
            args: ""
            name: windows
            arch: x86_64
    runs-on: ${{ matrix.platform }}
    steps:
      - name: 克隆仓库
        uses: actions/checkout@v4.2.0
      - name: 缓存 Cargo 产物
        uses: actions/cache@v4.2.3
        with:
          path: >
            ~/.cargo/bin/

            ~/.cargo/registry/index/

            ~/.cargo/registry/cache/

            ~/.cargo/git/db/

            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: 安装 PNPM
        uses: pnpm/action-setup@v4.0.0
      - name: 安装 Node.js
        uses: actions/setup-node@v4.0.4
        with:
          node-version: lts/*
          cache: pnpm
      - name: 安装 Rust 工具链
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}
      - name: 安装 wasm32 目标
        run: rustup target add wasm32-unknown-unknown
      - name: 安装前端依赖
        run: pnpm i
      - name: 构建前端
        run: pnpm build
      - name: 构建 AMLL TTML Tools 程序并发布自动构建
        uses: tauri-apps/tauri-action@v0.5.15
        with:
          tagName: ${{ github.ref_name }}-dev
          includeUpdaterJson: true
          releaseName: AMLL TTML Tools ${{ github.ref_name }} branch development build
          releaseBody: >
            Latest ${{ github.ref_name }} branch development build.

            最新 ${{ github.ref_name }} 分支开发调试构建。

            Development version may be unstable and may not work properly, please only for test purpose.

            开发版本可能不稳定且可能无法正常工作，请仅用于测试目的。


            Latest commits (最新提交): ${{ github.event.head_commit.message }}
          prerelease: true
          args: ${{ matrix.args }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 上传产物到 Action Artifact
        uses: actions/upload-artifact@v4.4.0
        with:
          name: AMLL TTML Tools ${{matrix.name}}-${{matrix.arch}}
          path: >
            src-tauri/target/**/release/bundle/**/*

            src-tauri/target/**/release/AMLL TTML Tool.exe

            src-tauri/target/**/release/AMLL TTML Tool
